drop table if exists users CASCADE;
create table users (
    id bigint generated by default as identity,
    username varchar(45) not null,
    password varchar(45) not null,
    enabled int not null,
    primary key (id)
);

drop table if exists authorities CASCADE;
create table authorities (
    id bigint generated by default as identity,
    username varchar(45) not null,
    authority varchar(45) not null,
    primary key (id)
);